<?xml version="1.0" encoding="utf-8"?><Database Name="DisplayMeter" Class="DisplayMeter_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLEXPRESS2012;Initial Catalog=DisplayMeter;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DisplayMeterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mas_Lack" Member="mas_Lacks">
    <Type Name="mas_Lack">
      <Column Name="LackUniq" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LackDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LackIPAddress" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LackSorting" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="mas_Lack_tran_LogMeter" Member="tran_LogMeters" ThisKey="LackUniq" OtherKey="LackUniq" Type="tran_LogMeter" />
    </Type>
  </Table>
  <Table Name="dbo.sec_User" Member="sec_Users">
    <Type Name="sec_User">
      <Column Name="UserUniq" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Passwd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="sec_User_tran_LogMeter" Member="tran_LogMeters" ThisKey="UserName" OtherKey="UserName" Type="tran_LogMeter" />
    </Type>
  </Table>
  <Table Name="dbo.tran_LogMeter" Member="tran_LogMeters">
    <Type Name="tran_LogMeter">
      <Column Name="LogUniq" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LackUniq" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter1" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter2" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter3" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter4" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="mas_Lack_tran_LogMeter" Member="mas_Lack" ThisKey="LackUniq" OtherKey="LackUniq" Type="mas_Lack" IsForeignKey="true" />
      <Association Name="sec_User_tran_LogMeter" Member="sec_User" ThisKey="UserName" OtherKey="UserName" Type="sec_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.stp_get_LastMeter" Method="stp_get_LastMeter">
    <ElementType Name="stp_get_LastMeterResult">
      <Column Name="LackUniq" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LackDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LackIPAddress" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LackSorting" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LogMeter1" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter2" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter3" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter4" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_get_LastMeter_ByUniq" Method="stp_get_LastMeter_ByUniq">
    <Parameter Name="LackUniq" Parameter="lackUniq" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="stp_get_LastMeter_ByUniqResult">
      <Column Name="LackUniq" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LackDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LackIPAddress" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LackSorting" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LogMeter1" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter2" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter3" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LogMeter4" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>